config/routes.rb
Rails.application.routes.draw do
  root "clients#index"

  
  resources :clients do 
    resources :lifts
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :lifts
end

app/models/lift.rb
class Lift < ApplicationRecord
    belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :find_client, only: [:show, :edit, :update, :destroy]

    def index
        @clients = Client.all
    end

    def show
    end

    def new
        @client = Client.new
    end

    def create
        @client = Client.create(client_params)
        if @client.save
            redirect_to client_path(@client)
        else 
            render :new
        end
    end 

    def edit
    end

    def update
        if @client.update(client_params)
          redirect_to client_path( @client)
        else 
           render :edit
        end
    end

    def destroy
        @client.destroy 
        redirect_to clients_path
    end

    private

    def client_params
        params.require(:client).permit(:name)
    end

    def find_client
        @client = Client.find_by(id: params[:id])
    end


end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
    before_action :find_lift, only: [:show, :edit, :update, :destroy]
        def index
            if params[:client_id] && @client = Client.find_by(id: params[:client_id])
                @lifts = @client.lifts.all
            end
        end
    
        def show
        end
    
        def new
            if params[:client_id] && @client = Client.find_by(id: params[:client_id])
                
                @lift = @client.lifts.build
            end
        end
    
        def create
            if params[:client_id] && @client = Client.find_by(id: params[:client_id])
                @lift = @client.lifts.build(lift_params)
            end
            if @lift.save
                redirect_to client_lift_path(@lift.client, @lift)
            end
        end
    
        def edit
        
        end
    
        def update
            if @lift.update(lift_params)
                redirect_to client_lift_path(@lift.client, @lift)
            else
                render :edit 
            end
        end
    
        def destroy
            @lift.destroy
            redirect_to client_path(@lift.client)
        end
    
        private
    
        def lift_params
            params.require(:lift).permit(:client_id, :name, :weight, :ROM, :repetitions, :date, :notes)
        end
        def find_lift
            @lift = Lift.find_by(id: params[:id])
            @client = @lift.client
        end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/lifts_helper.rb
module LiftsHelper
end

app/views/clients/_form.html.erb
<% if @client.errors.any? %>
<ul>
  <% @client.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%=form_for (@client) do |f|%>
<%=f.label :name%>
<%=f.text_field :name%>
<%=f.submit%>
<%end %>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
<%= render 'form' %>

app/views/clients/index.html.erb
<h1> Client index </h1>
<%@clients.each do |c|%>
    <%= link_to c.name , client_path(c) %>
    <br>
<%end%>
<br>
<%= link_to 'Add New Client', new_client_path %>
<br>

app/views/clients/new.html.erb
<h1>New Client</h1>
<%= render 'form' %>

app/views/clients/show.html.erb
<h1><%=@client.name%></h1>
<%@client.lifts.each do |lift|%>
<%= link_to lift.name, client_lift_path(@client, lift) %>
<br>
<%end%>
<br>
<%= link_to 'add lift', new_client_lift_path(@client.id) %>
<%= link_to 'Remove Client', client_path(@client), method: "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChrisBradyStrengthProgressTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= link_to 'Home', root_path %>
    <%= yield %>
  </body>
</html>

app/views/lifts/_form.html.erb
<% if @lift.errors.any? %>
<ul>
  <% @lift.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%=form_for ([@client, @lift]) do |f|%>
<%=f.label :name%>
<%=f.text_field :name%>
<br>
<%=f.label :weight %>
<%=f.number_field :weight%>
<br>
<%=f.label :repetitions %>
<%=f.number_field :repetitions %>
<br>
<%=f.label :ROM %>
<%=f.text_field :ROM %>
<br>
<%=f.label :date %>
<%=f.datetime_select :date, start_year: 2017%>
<br>
<%=f.label :notes%>
<%=f.text_area :notes %>
<%=f.submit%>
<%end %>

app/views/lifts/edit.html.erb
<h1>Edit Lift</h1>
<%= render 'form' %>

app/views/lifts/new.html.erb
<h1>New Lift</h1>
<%= render 'form' %>

app/views/lifts/show.html.erb
<h1><%=@lift.name%> <%=@lift.ROM%></h1>
<ul>
    <li><%=@lift.weight%>lbs</li>
    <li>For <%=@lift.repetitions%></li>
    <li>On <%=@lift.date%></li>
</ul>
<h2>Notes about this lift<h2>
<%=@lift.notes%>
<br>
<%= link_to 'Delete Lift', client_lift_path(@lift.client_id, @lift.id), method: "delete" %>
<br>
<%= link_to 'Add New Lift', new_client_lift_path(@lift.client_id, @lift) %>
<br>
<%= link_to 'Edit Lift', edit_client_lift_path(@lift.client_id, @lift) %>